// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using com_parsan_student.Models;

namespace com_parsan_student.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("com_parsan_student.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Family")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Family = "Alavi",
                            Name = "Ali"
                        },
                        new
                        {
                            Id = 2,
                            Family = "Mohammadi",
                            Name = "Mohammad"
                        },
                        new
                        {
                            Id = 3,
                            Family = "Mahmoodi",
                            Name = "Hadi"
                        },
                        new
                        {
                            Id = 4,
                            Family = "khalili",
                            Name = "Mahdi"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
